global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'Bot'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8091', 'localhost:8092']
  - job_name: 'Scrapper'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:8092' ]
