springdoc:
  swagger-ui:
    path: "swagger-ui"

management:
  server:
    port: 8080

server:
  port: 8083

app:
  bot:
    name: "tinkoff-bot"
    token: ${BOT_TOKEN}
  scrapper:
    url: "http://localhost:8080"
  scrapper-queue:
      name: "updates.queue"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${QUEUE_USERNAME}
    password: ${QUEUE_PASSWORD}
