on:
  push:
    paths:
      - 'bot/**'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/bot.yml'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Jar
        run: mvn package -pl bot -am
      - name: Build Image
        run: docker build -t wieceslaw/bot-app:latest . -f bot/bot.Dockerfile
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker push ${{ env.REGISTRY }}/bot:latest
