on:
  push:
    paths-ignore:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build JOOQ
        run: mvn package -pl scrapper-jooq
      - name: Show package
        run: ls -la
      - name: Show package
        run: ls -la target
      - name: Generate JOOQ
        run: java -jar /scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar
      - name: Build
        run: mvn package -pl scrapper -am
