on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/scrapper.yml'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build JOOQ
        run: mvn package -pl scrapper-jooq -am
      - name: Generate JOOQ
        run: java -jar scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar
      - name: Build Jar
        run: mvn package -pl scrapper -am
      - name: Build Image
        run: docker build -t ghcr.io/wieceslaw/scrapper-app:latest . -f scrapper/scrapper.Dockerfile
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: docker push ghcr.io/wieceslaw/scrapper-app:latest