on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'migrations'
      - 'link-parser/**'
      - 'pom.xml'
      - '.github/workflows/scrapper.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build JOOQ
        run: mvn package -pl scrapper-jooq
      - name: Generate JOOQ
        run: java -jar scrapper-jooq/target/scrapper-jooq-1.0-SNAPSHOT.jar
      - name: Build Jar
        run: mvn package -pl scrapper -am
      - name: Build
        run: mvn package -pl scrapper -am
      - name: Build Image
        run: docker build -t wieceslaw/scrapper-app:latest . -f scrapper/scrapper.Dockerfile